const list: ParfumType = {
    Purity: {
        Alle: new Set(),
        Kopfnoten: new Set(["Blutorange", "Zitrone", "Bergamotte", "Mango", "Litschi"]),
        Herznoten: new Set(["Rote Früchte", "Ananas", "Jasmin"]),
        Basisnoten: new Set(["Weißer Moschuss", "Amber", "Madagaskarvanille", "Sandelholz"]),
        Jahreszeit: new Set<Jahr>(["Frühling", "Sommer", "Kältere Tage"]),
        Anlass: new Set<Anlass>(["Ganztägig", "Tagsüber", "Abends", "Freizeit", "Essen"]),
    },
    Agera: {
        Alle: new Set(),
        Kopfnoten: new Set(["Ananas", "Orange", "Zitrone", "Hyanzinthe"]),
        Herznoten: new Set(["Jasmin", "Iris", "Rosa Pfeffer"]),
        Basisnoten: new Set(["Patchouli", "Moschus", "Vanille", "Amber", "Vetiver"]),
        Jahreszeit: new Set<Jahr>(["Frühling", "Herbst"]),
        Anlass: new Set<Anlass>(["Sportlich", "Freizeit", "Tagsüber"]),
    },
    Karaz: {
        Alle: new Set(),
        Kopfnoten: new Set(["Schwarzkirsche", "Kirschlilör", "Bittermandel"]),
        Herznoten: new Set(["Griotte-Sirup", "Türkische Rose", "Jasmin Sambac"]),
        Basisnoten: new Set(["Peru-Balsam", "Geröstete Tonkabohne", "Sandelholz", "Vetiver", "Zeder"]),
        Jahreszeit: new Set<Jahr>(["Herbst", "Winter"]),
        Anlass: new Set<Anlass>(["Formell", "Verabredung", "Abends"]),
    },
    Thanos: {
        Alle: new Set(),
        Kopfnoten: new Set(["Lavendel", "Bergamotte", "Zitrone"]),
        Herznoten: new Set(["Honig", "Kaschmir", "Jasmin", "Zimt"]),
        Basisnoten: new Set(["Tabak", "Tonkabohne", "Vanille"]),
        Jahreszeit: new Set<Jahr>(["Herbst", "Winter"]),
        Anlass: new Set<Anlass>(["Abends", "Anlass"]),
    },
    Darwin: {
        Alle: new Set(),
        Kopfnoten: new Set(["Feigenblatt", "Kakao"]),
        Herznoten: new Set(["Kokosnuss"]),
        Basisnoten: new Set(["Patchouli", "Zeder"]),
        Jahreszeit: new Set<Jahr>(["Herbst", "Winter"]),
        Anlass: new Set<Anlass>(["Ganztägig", "Tagsüber", "Abends", "Alltag", "Formell", "Ganztägig"]),
    },
    Arabs: {
        Alle: new Set(),
        Kopfnoten: new Set(["Bergamotte", "Orange", "Zitrone", "Oud"]),
        Herznoten: new Set(["Jasmin", "Zeder", "Zimt", "Patchouli"]),
        Basisnoten: new Set(["Tonkabohne", "Scharzer Moschus", "Vanille", "Amber", "Sandelholz"]),
        Jahreszeit: new Set<Jahr>(["Winter", "Herbst"]),
        Anlass: new Set<Anlass>(["Abends", "Luxeriös"]),
    },
    Smoke: {
        Alle: new Set(),
        Kopfnoten: new Set(["Tabakblatt", "Schwarzer Pfeffer", "Bergamotte", "Kardamom"]),
        Herznoten: new Set(["Tonkabohne", "Tabakblüte", "Vanille", "Kakao"]),
        Basisnoten: new Set(["Vanille", "Oud", "Sandelholz"]),
        Jahreszeit: new Set<Jahr>(["Herbst", "Winter"]),
        Anlass: new Set<Anlass>(["Abends", "Ausgehen"]),
    },
    Xenon: {
        Alle: new Set(),
        Kopfnoten: new Set(["Kalabrische Bergamotte", "Pfeffer"]),
        Herznoten: new Set(["Pfeffer", "Lavendel", "Patchouli", "Geranie", "Vetiver", "Rosa Pfeffer"]),
        Basisnoten: new Set(["Ambroxan", "Zeder"]),
        Jahreszeit: new Set<Jahr>(["Ganzjährig", "Frühling", "Sommer", "Herbst", "Winter"]),
        Anlass: new Set<Anlass>(["Ganztägig", "Tagsüber", "Abends", "Ganztägig"]),
    },
    Over: {
        Alle: new Set(),
        Kopfnoten: new Set(["Kardamom", "Rosa Pfeffer", "Minze", "Veilchen"]),
        Herznoten: new Set(["Salbei", "Melone", "Lavendel", "Ananas"]),
        Basisnoten: new Set(["Kastanie", "Vanille", "Zeder", "Amberholz"]),
        Jahreszeit: new Set<Jahr>(["Ganzjährig", "Frühling", "Sommer", "Herbst", "Winter"]),
        Anlass: new Set<Anlass>(["Ganztägig", "Tagsüber", "Abends", "Sportlich", "Alltag"]),
    },
    Gaba: {
        Alle: new Set(),
        Kopfnoten: new Set(["Kardamom", "Arabischer Jasmin", "Safran"]),
        Herznoten: new Set(["Schwarzes Leder", "Patchouli", "Vetiver"]),
        Basisnoten: new Set(["Weißer Moschus", "Amber"]),
        Jahreszeit: new Set<Jahr>(["Ganzjährig", "Frühling", "Winter"]),
        Anlass: new Set<Anlass>(["Formell", "Abends", "Alltag"]),
    },
    IG: {
        Alle: new Set(),
        Duftnoten: new Set(["Chinesischer Schwarztee", "Bergamotte", "Ambrox", "Zimt", "Ingwer", "Zedernholz"]),
        Jahreszeit: new Set<Jahr>(["Frühling", "Sommer"]),
        Anlass: new Set<Anlass>(["Tagsüber", "Alltag", "Elegant"]),
    },
    Dubai: {
        Alle: new Set(),
        Duftnoten: new Set(["Oud", "Benzoe", "Patchouli", "Weihrauch", "Schwarzer Moschus"]),
        Jahreszeit: new Set<Jahr>(["Herbst", "Winter"]),
        Anlass: new Set<Anlass>(["Formell", "Abends", "Ausgehen"]),
    },
    Fahros: {
        Alle: new Set(),
        Kopfnoten: new Set(["Zeder", "Kamille", "Lavendel", "Mandarine", "Bergamotte", "Zitrone", "Muskatblüte"]),
        Herznoten: new Set(["Veilchenblatt", "Zeder", "Muskatnuss", "Sandelholz", "Nelke", "Jasmin", "Maiglöckchen"]),
        Basisnoten: new Set(["Leder", "Moschus", "Patchouli", "Amber", "Tonkabohne", "Vetiver"]),
        Jahreszeit: new Set<Jahr>(["Frühling", "Herbst", "Winter"]),
        Anlass: new Set<Anlass>(["Abends", "Anlass"]),
    },
    Assasin: {
        Alle: new Set(),
        Kopfnoten: new Set(["Bergamotte", "Schwarze Johannisbeere", "Ananas", "Apfel"]),
        Herznoten: new Set(["Wacholerbeeren", "Birke", "Patchouli", "Jasmin", "Rose"]),
        Basisnoten: new Set(["Mochus", "Eichenmoos", "Ambra", "Vanille"]),
        Jahreszeit: new Set<Jahr>(["Ganzjährig", "Frühling", "Sommer", "Herbst", "Winter"]),
        Anlass: new Set<Anlass>(["Formell"]),
    },
    Bless: {
        Alle: new Set(),
        Kopfnoten: new Set(["Meeresnoten", "Grapefruit"]),
        Herznoten: new Set(["Lorbeerblatt", "Jasmin"]),
        Basisnoten: new Set(["Ambra", "Patchouli", "Guajakholz", "Eichenmoos"]),
        Jahreszeit: new Set<Jahr>(["Frühling", "Sommer"]),
        Anlass: new Set<Anlass>(["Tagsüber", "Sportlich", "Elegant"]),
    },
    Zucker: {
        Alle: new Set(),
        Kopfnoten: new Set(["Elemiharz"]),
        Herznoten: new Set(["Provenzalischer Lavendel"]),
        Basisnoten: new Set(["Leder"]),
        Jahreszeit: new Set<Jahr>(["Ganzjährig", "Herbst", "Winter"]),
        Anlass: new Set<Anlass>(["Ganztägig", "Tagsüber", "Abends", "Formell", "Leger"]),
    },
    Sky: {
        Alle: new Set(),
        Duftnoten: new Set([
            "Zitrone",
            "Mandarine",
            "Sandelholz",
            "Holzige Noten",
            "Zeder",
            "Tonkabohne",
            "Vetiver",
            "Vanille",
        ]),
        Jahreszeit: new Set<Jahr>(["Ganzjährig"]),
        Anlass: new Set<Anlass>(["Alltag", "Abends"]),
    },
    "Oud King": {
        Alle: new Set(),
        Kopfnoten: new Set(["Bergamotte"]),
        Basisnoten: new Set(["Oud", "Schwarzer Moschus"]),
        Jahreszeit: new Set<Jahr>(["Frühling", "Herbst", "Winter"]),
        Anlass: new Set<Anlass>(["Abends", "Formell"]),
    },
    Oudy: {
        Alle: new Set(),
        Basisnoten: new Set(["Oud", "Schwarzer Muschus", "Patchouli"]),
        Jahreszeit: new Set<Jahr>(["Herbst", "Winter"]),
        Anlass: new Set<Anlass>(["Formell", "Abends"]),
    },
    Ocean: {
        Alle: new Set(),
        Kopfnoten: new Set(["Meeresnoten", "Bergamotte", "Zitrone"]),
        Herznoten: new Set(["Rosmarin", "Salbei", "Geranie"]),
        Basisnoten: new Set(["Weihrauch", "Patchouli", "Sandelholz"]),
        Jahreszeit: new Set<Jahr>(["Frühling", "Sommer"]),
        Anlass: new Set<Anlass>(["Tagsüber", "Leger"]),
    },
    Colombos: {
        Alle: new Set(),
        Kopfnoten: new Set(["Blutorange", "Pfefferminze"]),
        Herznoten: new Set(["Zimt", "Rosen-Absolue"]),
        Basisnoten: new Set(["Amberketal", "Leder"]),
        Jahreszeit: new Set<Jahr>(["Ganzjährig", "Herbst", "Winter"]),
        Anlass: new Set<Anlass>(["Ganztägig", "Tagsüber", "Abends"]),
    },
    "Bad Lady": {
        Alle: new Set(),
        Kopfnoten: new Set(["Bergamotte", "Zitrone", "Mandel", "Kaffee"]),
        Herznoten: new Set(["Bulgarische Rose", "Arabischer Jasmin", "Tuberose", "Orangenblüte"]),
        Basisnoten: new Set([
            "Tonkabohne",
            "Kakao",
            "Vanille",
            "Praline",
            "Sandelholz",
            "Amber",
            "Kaschmirholz",
            "Weißer Moschus",
        ]),
        Jahreszeit: new Set<Jahr>(["Ganzjährig", "Frühling", "Sommer", "Herbst", "Winter"]),
        Anlass: new Set<Anlass>(["Tagsüber", "Ausgehen", "Anlass"]),
    },
    // ! Seite 5
    // "1974": {
    //     Alle: new Set(),
    //     Kopfnoten: new Set(["Ylang-Ylang", "Neroli", "Zitrusfrüchte"]),
    //     Herznoten: new Set(["Jasmin", "Rosen", "Iris"]),
    //     Basisnoten: new Set(["Sandelholz"]),
    //     Jahreszeit: new Set<Jahr>([]),
    //     Anlass: new Set<Anlass>([]),
    // },
    Zahra: {
        Alle: new Set(),
        Kopfnoten: new Set(["Mandarine", "Bergamotte", "Weißer Pfirsich", "Ingwer", "Pfeffer"]),
        Herznoten: new Set(["Tuberose", "Jasmin", "Rose", "Patchouli"]),
        Basisnoten: new Set(["Vanille", "Amber", "Zedernholz", "Weißer Moschus", "Sandelholz"]),
        Jahreszeit: new Set<Jahr>(["Frühling", "Sommer"]),
        Anlass: new Set<Anlass>(["Tagsüber", "Leger"]),
    },
    Orchid: {
        Alle: new Set(),
        Kopfnoten: new Set(["Ylang-Ylang", "Jasmin", "Bergamotte", "Mandarine", "Zitrone", "Schwarze Johannisbeere"]),
        Herznoten: new Set(["Orchidee", "Fruchtige Noten", "Ylang-Ylang", "Gardenie", "Gewürze", "Lotus", "Jasmin"]),
        Basisnoten: new Set(["Patchouli", "Schokolade", "Vanille", "Weihrauch"]),
        Jahreszeit: new Set<Jahr>(["Herbst", "Winter"]),
        Anlass: new Set<Anlass>(["Abends", "Anlass"]),
    },
    "Pour Femme": {
        Alle: new Set(),
        Kopfnoten: new Set(["Bergamotte", "Zitrone", "Mandel", "Kaffe"]),
        Herznoten: new Set(["Bulgarische Rose", "Arabischer Jasmin", "Toberose", "Orangenblüte"]),
        Basisnoten: new Set(["Tonkabohne", "Kakao", "Vanille", "Praline", "Sandelholz", "Amber", "Kaschmirholz", "Weißer Moschus"]),
        Jahreszeit: new Set<Jahr>(["Frühling", "Sommer"]),
        Anlass: new Set<Anlass>(["Ganztägig", "Leger", "Elegant"]),
    },
    Cleopatra: {
        Alle: new Set(),
        Kopfnoten: new Set(["Pfeffer", "Zimt", "Ingwer"]),
        Herznoten: new Set(["Rosenblatt", "Iris", "Lavendel"]),
        Basisnoten: new Set(["Patchouli", "Tabak"]),
        Jahreszeit: new Set<Jahr>(["Ganzjährig", "Frühling", "Sommer", "Herbst", "Winter"]),
        Anlass: new Set<Anlass>(["Leger", "Anlass"]),
    },
    Sultana: {
        Alle: new Set(),
        Kopfnoten: new Set(["Bergamotte", "Schwarze Johannisbeere", "Grüner Apfel", "Rosa Pfeffer"]),
        Herznoten: new Set(["Jasmin", "Rosenblätter", "Toberose", "Safran"]),
        Basisnoten: new Set(["Sandelholz", "Amber", "Vanille"]),
        Jahreszeit: new Set<Jahr>(["Frühling", "Sommer"]),
        Anlass: new Set<Anlass>(["Tagsüber"]),
    },
    Musky: {
        Alle: new Set(),
        Kopfnoten: new Set(["Passionsfrucht", "Davana"]),
        Herznoten: new Set(["Gardenie", "Tuberose"]),
        Basisnoten: new Set(["Ambra", "Vanille"]),
        Jahreszeit: new Set<Jahr>(["Ganzjährig", "Frühling", "Sommer", "Herbst", "Winter"]),
        Anlass: new Set<Anlass>(["Tagsüber", "Leger", "Frisch"]),
    },
    Goldstaub: {
        Alle: new Set(),
        Duftnoten: new Set(["Vanille", "Amber", "Holz"]),
        Jahreszeit: new Set<Jahr>(["Herbst", "Winter"]),
        Anlass: new Set<Anlass>(["Ganztägig", "Tagsüber", "Abends", "Ausgehen"]),
    },
    Charm: {
        Alle: new Set(),
        Kopfnoten: new Set(["Mandarine", "Schwarzer Johannisbeere", "Petitgrain", "Lavendel"]),
        Herznoten: new Set(["Jasmin", "Lavendel", "Orangenblüte"]),
        Basisnoten: new Set(["Vanille", "Zeder", "Ambra", "Moschuss"]),
        Jahreszeit: new Set<Jahr>(["Ganzjährig", "Frühling", "Sommer"]),
        Anlass: new Set<Anlass>(["Ganztägig", "Alltag", "Ausgehen"]),
    },
    Evolue: {
        Alle: new Set(),
        Kopfnoten: new Set(["Apfelblatt", "Mandarine", "Osmanthus"]),
        Herznoten: new Set(["Boronia", "Mangnolie", "Freesie"]),
        Basisnoten: new Set(["Weißer Moschus", "Weiße Iris"]),
        Jahreszeit: new Set<Jahr>(["Frühling", "Sommer"]),
        Anlass: new Set<Anlass>(["Tagsüber", "Leger"]),
    },
    "La Rose": {
        Alle: new Set(),
        Kopfnoten: new Set(["Birne", "Bargamotte", "Mandarin"]),
        Herznoten: new Set(["Lilie", "Jasmin", "Pfingstrose"]),
        Basisnoten: new Set(["Bernstein", "Sandelholz", "Vanille"]),
        Jahreszeit: new Set<Jahr>(["Frühling", "Sommer"]),
        Anlass: new Set<Anlass>(["Tagsüber", "Abends", "Anlass"]),
    },
    // ! Seite 7
    // Yuno: {
    //     Alle: new Set(),
    //     Kopfnoten: new Set(["Safran", "Jasmin"]),
    //     Herznoten: new Set(["Amber"]),
    //     Basisnoten: new Set(["Fichtenharz", "Zedernholz"]),
    //     Jahreszeit: new Set<Jahr>([]),
    //     Anlass: new Set<Anlass>([]),
    // },
};

export default list;
